# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_delete_usermanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', to='first_app.User'),
        ),
    ]
